import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  pill: {
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(155,135,245,0.25)",
    marginBottom: 18,
  },
  pillText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#7B68EE",
    letterSpacing: 0.4,
  },
  title: {
    fontSize: 40,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 3,
    color: "#E0B48A",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    textAlign: "center",
    color: "#4C4C5C",
    marginHorizontal: 10,
    marginBottom: 28,
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 28,
  },
  featureCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  iconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F3ECFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#333547",
    marginBottom: 4,
  },
  cardBody: {
    fontSize: 11,
    color: "#777A8C",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 26,
  },
  primaryButton: {
    flex: 1.2,
    backgroundColor: "#8C5CF6",
    borderRadius: 999,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#8C5CF6",
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#D9CEFF",
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  secondaryButtonText: {
    color: "#7B68EE",
    fontSize: 14,
    fontWeight: "600",
  },
  exampleContainer: {
    backgroundColor: "#F4F6FF",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(194,203,255,0.6)",
  },
  exampleLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#7A7F95",
    marginBottom: 8,
  },
  exampleBubble: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 12,
  },
  exampleText: {
    fontSize: 12,
    color: "#55596C",
    lineHeight: 18,
  },
});

export default styles;